# Generated by Django 4.2.28 on 2026-02-14 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("max_weight_kg", models.IntegerField()),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "vehicles",
                "ordering": ["base_price"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("quick", "Quick Send"),
                            ("multi", "Multi-Drop"),
                            ("bulk", "Bulk Import"),
                        ],
                        default="quick",
                        max_length=10,
                    ),
                ),
                ("pickup_address", models.TextField()),
                ("sender_name", models.CharField(max_length=255)),
                ("sender_phone", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet", "Wallet"),
                            ("cash_on_pickup", "Cash on Pickup"),
                            ("receiver_pays", "Receiver Pays"),
                        ],
                        default="wallet",
                        max_length=20,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Assigned", "Assigned"),
                            ("Started", "Started"),
                            ("Done", "Done"),
                            ("CustomerCanceled", "Customer Canceled"),
                            ("RiderCanceled", "Rider Canceled"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scheduled_pickup_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="orders.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dropoff_address", models.TextField()),
                ("receiver_name", models.CharField(max_length=255)),
                ("receiver_phone", models.CharField(max_length=20)),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("Box", "Box"),
                            ("Envelope", "Envelope"),
                            ("Fragile", "Fragile"),
                            ("Food", "Food"),
                            ("Document", "Document"),
                            ("Other", "Other"),
                        ],
                        default="Box",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("InTransit", "In Transit"),
                            ("Delivered", "Delivered"),
                            ("Failed", "Failed"),
                            ("Canceled", "Canceled"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.IntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "deliveries",
                "ordering": ["order", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created_at", "status"], name="orders_created_8f273d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "-created_at"], name="orders_user_id_535113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["order", "sequence"], name="deliveries_order_i_a42b7c_idx"
            ),
        ),
    ]
