# Generated by Django 4.2.28 on 2026-02-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('quick', 'Quick Send'), ('multi', 'Multi-Drop'), ('bulk', 'Bulk Import')], default='quick', max_length=10)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('cash', 'Cash'), ('cash_on_pickup', 'Cash on Pickup'), ('receiver_pays', 'Receiver Pays')], default='wallet', max_length=20)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance in kilometers', max_digits=10, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Total duration in minutes', null=True)),
                ('escrow_held', models.BooleanField(default=False, help_text='Whether funds are held in escrow')),
                ('escrow_released', models.BooleanField(default=False, help_text='Whether escrow funds have been released')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('PickedUp', 'Picked Up'), ('Started', 'Started'), ('Arrived', 'Arrived'), ('Done', 'Done'), ('CustomerCanceled', 'Customer Canceled'), ('RiderCanceled', 'Rider Canceled'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('is_relay_order', models.BooleanField(default=False, help_text='True when this order is split into multiple relay legs')),
                ('relay_legs_count', models.IntegerField(default=0, help_text='Total number of relay legs (0 for standard single-rider orders)')),
                ('routing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='ready', help_text='Async relay routing status (only meaningful for relay orders)', max_length=20)),
                ('routing_error', models.TextField(blank=True, default='', help_text='Error details when relay routing fails')),
                ('notes', models.TextField(blank=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to='dispatcher.rider')),
                ('suggested_rider', models.ForeignKey(blank=True, help_text='Suggested first-leg rider for relay orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for_orders', to='dispatcher.rider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_weight_kg', models.IntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Legacy flat rate (deprecated)', max_digits=10)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, help_text='Base fare for any delivery', max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Rate charged per kilometer', max_digits=10)),
                ('rate_per_minute', models.DecimalField(decimal_places=2, default=0, help_text='Rate charged per minute', max_digits=10)),
                ('min_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Minimum distance covered by base fare/min fee', max_digits=10)),
                ('min_fee', models.DecimalField(decimal_places=2, default=0, help_text='Minimum fee charged for any trip', max_digits=10)),
                ('pricing_tiers', models.JSONField(blank=True, help_text="Tiered pricing config, e.g. {type:'tiered', floor_km:6, floor_fee:1700, tiers:[{max_km:10,rate:275},...]}", null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['base_fare'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'db_table': 'order_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.vehicle'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_address', models.TextField(blank=True, default='')),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_phone', models.CharField(blank=True, default='', max_length=20)),
                ('dropoff_address', models.TextField()),
                ('dropoff_latitude', models.FloatField(blank=True, null=True)),
                ('dropoff_longitude', models.FloatField(blank=True, null=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('Box', 'Box'), ('Envelope', 'Envelope'), ('Fragile', 'Fragile'), ('Food', 'Food'), ('Document', 'Document'), ('Other', 'Other')], default='Box', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cod_from', models.CharField(choices=[('sender', 'Sender'), ('customer', 'Customer / Receiver')], default='customer', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InTransit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sequence', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='OrderLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leg_number', models.PositiveIntegerField(help_text='Sequential leg number starting at 1')),
                ('distance_km', models.FloatField(default=0.0, help_text='Road distance for this leg')),
                ('duration_minutes', models.IntegerField(default=0)),
                ('rider_payout', models.DecimalField(decimal_places=2, default=0, help_text='Pre-calculated payout amount for this leg', max_digits=10)),
                ('zone_compliance_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Bonus applied when rider stays within their assigned zone path', max_digits=10)),
                ('hub_pin', models.CharField(blank=True, default='', help_text='PIN generated at leg creation; hub agent confirms before handoff', max_length=6)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('PickedUp', 'Picked Up'), ('InTransit', 'In Transit'), ('AtHub', 'At Hub'), ('Completed', 'Completed'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('dropped_at_hub_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_relay_node', models.ForeignKey(blank=True, help_text='Null for last leg (delivers to order destination)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_legs', to='dispatcher.relaynode')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='orders.order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_legs', to='dispatcher.rider')),
                ('start_relay_node', models.ForeignKey(blank=True, help_text='Null for first leg (pickup from order origin)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_legs', to='dispatcher.relaynode')),
            ],
            options={
                'db_table': 'order_legs',
                'ordering': ['order', 'leg_number'],
                'unique_together': {('order', 'leg_number')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at', 'status'], name='orders_created_8f273d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_user_id_535113_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['order', 'sequence'], name='deliveries_order_i_a42b7c_idx'),
        ),
    ]
