# Generated by Django 4.2.28 on 2026-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["base_fare"]},
        ),
        migrations.AddField(
            model_name="order",
            name="distance_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total distance in kilometers",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="duration_minutes",
            field=models.IntegerField(
                blank=True, help_text="Total duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="base_fare",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Base fare for any delivery",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="rate_per_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate charged per kilometer",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="rate_per_minute",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate charged per minute",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Legacy flat rate (deprecated)",
                max_digits=10,
            ),
        ),
    ]
