# Generated by Django 4.2.3 on 2026-02-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_delivery_pickup_address_delivery_pickup_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="pricing_tiers",
            field=models.JSONField(
                blank=True,
                help_text="Tiered pricing config, e.g. {type:'tiered', floor_km:6, floor_fee:1700, tiers:[{max_km:10,rate:275},...]}",
                null=True,
            ),
        ),
    ]
