# Generated by Django 4.2.28 on 2026-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_orderleg_suggested_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.CharField(blank=True, default='', help_text='Reason the delivery failed', max_length=255),
        ),
    ]
