# Generated by Django 4.2.28 on 2026-03-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_event_created_by_old_new_value'),
        ('orders', '0016_delivery_failure_reason'),
    ]

    operations = [
    ]
