# Generated by Django 4.2.28 on 2026-02-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(default='Wema Bank', max_length=100)),
                ('bank_code', models.CharField(default='000017', max_length=10)),
                ('corebanking_account_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('paystack_status', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('corebanking', 'CoreBanking (LibertyPay)'), ('paystack', 'Paystack')], db_index=True, max_length=20)),
                ('payload', models.JSONField(help_text='Complete webhook payload as received')),
                ('headers', models.JSONField(blank=True, help_text='HTTP headers from webhook request', null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='received', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('error_traceback', models.TextField(blank=True, help_text='Full error traceback for debugging', null=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('recipient_account_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('signature_received', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, help_text='Transaction created from this webhook (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='wallet.transaction')),
            ],
            options={
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='webhook_log_created_5dbdab_idx'), models.Index(fields=['source', '-created_at'], name='webhook_log_source_19b7ea_idx'), models.Index(fields=['status', '-created_at'], name='webhook_log_status_4b788b_idx'), models.Index(fields=['transaction_reference'], name='webhook_log_transac_1eb85b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='transaction_created_cf5536_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__efd4a5_idx'),
        ),
    ]
