# Generated by Django 4.2.28 on 2026-02-18 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(default="Wema Bank", max_length=100)),
                ("bank_code", models.CharField(default="000017", max_length=10)),
                (
                    "corebanking_account_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "virtual_accounts",
                "ordering": ["-created_at"],
            },
        ),
    ]
