# Generated by Django 4.2.28 on 2026-02-20 14:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_add_virtual_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("corebanking", "CoreBanking (LibertyPay)"),
                            ("paystack", "Paystack"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Complete webhook payload as received"),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True,
                        help_text="HTTP headers from webhook request",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True,
                        help_text="Full error traceback for debugging",
                        null=True,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "recipient_account_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("signature_valid", models.BooleanField(blank=True, null=True)),
                (
                    "signature_received",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transaction created from this webhook (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="wallet.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="webhook_log_created_5dbdab_idx"
                    ),
                    models.Index(
                        fields=["source", "-created_at"],
                        name="webhook_log_source_19b7ea_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="webhook_log_status_4b788b_idx",
                    ),
                    models.Index(
                        fields=["transaction_reference"],
                        name="webhook_log_transac_1eb85b_idx",
                    ),
                ],
            },
        ),
    ]
