from django.urls import path

from .admin_views import (
    AdminHubDetailView,
    AdminHubListCreateView,
    AdminRiderAssignHubView,
    AdminVerticalLeadDetailView,
    AdminVerticalLeadListAssignView,
    AdminZoneCaptainDetailView,
    AdminZoneCaptainListAssignView,
    AdminZoneDetailView,
    AdminZoneListCreateView,
    AdminZoneTargetDetailView,
    AdminZoneTargetListCreateView,
)
from .views import (
    DashboardFlagsView,
    DashboardSummaryView,
    JumiaHubsListView,
    KmIntegrityView,
    KmVisibilityView,
    LeaderboardsView,
    MerchantsListView,
    OperationsMeView,
    OrdersAnalyticsView,
    OrdersListView,
    RiderDailyActivityView,
    RiderDetailView,
    RiderPerformanceView,
    RiderVehicleView,
    VehiclesListView,
    VerticalDetailView,
    VerticalListView,
    VerticalZonesView,
    ZoneDetailView,
    ZoneListView,
    ZoneRidersView,
)

urlpatterns = [
    path("me/", OperationsMeView.as_view(), name="operations-me"),
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="operations-dashboard-summary"),
    path("dashboard/flags/", DashboardFlagsView.as_view(), name="operations-dashboard-flags"),
    path("flags/", DashboardFlagsView.as_view(), name="operations-flags"),
    path("verticals/", VerticalListView.as_view(), name="operations-vertical-list"),
    path("verticals/<uuid:pk>/", VerticalDetailView.as_view(), name="operations-vertical-detail"),
    path("verticals/<uuid:pk>/zones/", VerticalZonesView.as_view(), name="operations-vertical-zones"),
    path("zones/", ZoneListView.as_view(), name="operations-zone-list"),
    path("zones/<uuid:pk>/", ZoneDetailView.as_view(), name="operations-zone-detail"),
    path("zones/<uuid:pk>/riders/", ZoneRidersView.as_view(), name="operations-zone-riders"),
    path("riders/<uuid:pk>/", RiderDetailView.as_view(), name="operations-rider-detail"),
    path("riders/<uuid:pk>/performance/", RiderPerformanceView.as_view(), name="operations-rider-performance"),
    path("riders/<uuid:pk>/daily-activity/", RiderDailyActivityView.as_view(), name="operations-rider-daily-activity"),
    path("leaderboards/", LeaderboardsView.as_view(), name="operations-leaderboards"),
    path("orders/", OrdersListView.as_view(), name="operations-orders"),
    path("orders/analytics/", OrdersAnalyticsView.as_view(), name="operations-orders-analytics"),
    path("merchants/", MerchantsListView.as_view(), name="operations-merchants"),
    path("jumia-hubs/", JumiaHubsListView.as_view(), name="operations-jumia-hubs"),
    path("vehicles/", VehiclesListView.as_view(), name="operations-vehicles"),
    path("riders/<uuid:pk>/vehicle/", RiderVehicleView.as_view(), name="operations-rider-vehicle"),
    path("km-visibility/", KmVisibilityView.as_view(), name="operations-km-visibility"),
    path("km-integrity/", KmIntegrityView.as_view(), name="operations-km-integrity"),
    path("admin/zones/", AdminZoneListCreateView.as_view(), name="operations-admin-zones"),
    path("admin/zones/<uuid:pk>/", AdminZoneDetailView.as_view(), name="operations-admin-zone-detail"),
    path("admin/hubs/", AdminHubListCreateView.as_view(), name="operations-admin-hubs"),
    path("admin/hubs/<uuid:pk>/", AdminHubDetailView.as_view(), name="operations-admin-hub-detail"),
    path("admin/zone-targets/", AdminZoneTargetListCreateView.as_view(), name="operations-admin-zone-targets"),
    path("admin/zone-targets/<uuid:pk>/", AdminZoneTargetDetailView.as_view(), name="operations-admin-zone-target-detail"),
    path("admin/vertical-leads/", AdminVerticalLeadListAssignView.as_view(), name="operations-admin-vertical-leads"),
    path("admin/vertical-leads/<uuid:pk>/", AdminVerticalLeadDetailView.as_view(), name="operations-admin-vertical-lead-detail"),
    path("admin/zone-captains/", AdminZoneCaptainListAssignView.as_view(), name="operations-admin-zone-captains"),
    path("admin/zone-captains/<uuid:pk>/", AdminZoneCaptainDetailView.as_view(), name="operations-admin-zone-captain-detail"),
    path("admin/riders/<uuid:pk>/hub/", AdminRiderAssignHubView.as_view(), name="operations-admin-rider-hub"),
]
